### PR TITLE
Guard against non-array responses passed to the 'get-facts' callback.

### PR DESCRIPTION
**Pull request by moisadoru**

### CODE REVIEW

**Comment by KrzysztofMadejski** [comment]
Hi @moisadoru ! Where are you from? How did you learn about this plugin?

**Comment by moisadoru** [comment]
@KrzysztofMadejski I'm from Bucharest, Romania, as you can see in my profile. I'm using the extension actively in Chrome, and occasionally I get an error in the console because this.facts being undefined. Hence this PR.

**Comment by KrzysztofMadejski** [comment]
Oh cool! Thank you fro this PR!

I'm not sure if this plugin is still maintained (summoning Cosmin via email) , but I'm glad to hear it is working! :D

You might be interested in checking out the https://github.com/kodujdlapolski/factchecker-plugin-chrome/ fork. We've taken the Romanian version, cleared out some bugs and rewritten the code in a way to be more replicable to other fact-checkers (standard API + some configs). We did also an extensive UX testing and remodelled some features (ie. Polish fact-checker is checking a lot of videos/podcasts so there is a need to show highlights around them). Sadly, the Polish fork is in a stall with several people committed to push it forward, but none of them having time.

**Comment by voidberg** [comment]
Looks good, thanks! Will need to make a new build and publish it.

**Pull request merged**
